version: '3.3'

services:
  db:
    image: mariadb
    restart: always
    env_file:
      - ./docker-compose.env

  ip-hit:
    build:
      context: .
    image: ip-hit
    ports:
      - '80:8000'
    command: php -S ip-hit:8000 -t public
    env_file:
      - ./docker-compose.env
    restart: always
