version: '3.3'

services:
  db:
    image: mariadb
    restart: always
    environment:
      - docker-compose.env

  ip-hit:
    build:
      context: .
    image: registry.gitlab.com/mamazary/ip-hit
    ports:
      - '80:80'
    env_file:
      - docker-compose.env
    restart: always
